//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.04 at 10:45:35 PM EST 
//

package org.myrobotlab.pickToLight;

/**
 * <p>
 * Java class for AddressType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="controller" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *       &lt;attribute name="I2CBus" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="I2CAddress" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class Address2 {

  protected String controller;
  protected int i2CBus;
  protected int i2CAddress;

  /**
   * Gets the value of the controller property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getController() {
    return controller;
  }

  /**
   * @return the value of the i2CAddress property.
   * 
   */
  public int getI2CAddress() {
    return i2CAddress;
  }

  /**
   * @return  the value of the i2CBus property.
   * 
   */
  public int getI2CBus() {
    return i2CBus;
  }

  /**
   * Sets the value of the controller property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setController(String value) {
    this.controller = value;
  }

  /*
   * Sets the value of the i2CAddress property.
   * 
   */
  public void setI2CAddress(int value) {
    this.i2CAddress = value;
  }

  /*
   * Sets the value of the i2CBus property.
   * 
   */
  public void setI2CBus(int value) {
    this.i2CBus = value;
  }

}
