# each of these lines creates and starts a service

arduino01 	= runtime.createAndStart("arduino01","Arduino")
audiofile01 	= runtime.createAndStart("audiofile01","AudioFile")
chessgame01 	= runtime.createAndStart("chessgame01","ChessGame")
clock01 	= runtime.createAndStart("clock01","Clock")
ipcamera01 	= runtime.createAndStart("ipcamera01","IPCamera")
jfugue01 	= runtime.createAndStart("jfugue01","JFugue")
python02 	= runtime.createAndStart("python02","Python")
logging01 	= runtime.createAndStart("logging01","Log")
motor01 	= runtime.createAndStart("motor01","Motor")
opencv01 	= runtime.createAndStart("opencv01","OpenCV")
remote01 	= runtime.createAndStart("remote01","RemoteAdapter")
sensor01 	= runtime.createAndStart("sensor01","SensorMonitor")
servo01 	= runtime.createAndStart("servo01","Servo")
speech01 	= runtime.createAndStart("speech01","Speech")
