!!org.myrobotlab.service.config.IndianTtsConfig
blocking: false
mute: false
peers:
  audioFile:
    autoStart: true
    name: indiantts.audioFile
    type: AudioFile
  http:
    autoStart: true
    name: indiantts.http
    type: HttpClient
speechRecognizers: null
substitutions: null
type: IndianTts
voice: null
