!!org.myrobotlab.service.config.VoiceRssConfig
blocking: false
mute: false
peers:
  audioFile:
    autoStart: true
    name: voicerss.audioFile
    type: AudioFile
speechRecognizers: null
substitutions: null
type: VoiceRss
voice: null
