!!org.myrobotlab.service.config.DockerConfig
autoDisable: false
clip: true
controller: null
enabled: true
idleTimeout: null
inverted: false
maxIn: 180.0
maxOut: 180.0
minIn: 0.0
minOut: 0.0
pin: null
rest: 90.0
speed: null
sweepMax: null
sweepMin: null
type: Docker
