!!org.myrobotlab.service.config.MarySpeechConfig
blocking: false
listeners: null
mute: false
peers:
  audioFile:
    autoStart: true
    name: maryspeech.audioFile
    type: AudioFile
speechRecognizers: null
substitutions: null
type: MarySpeech
voice: null
