#ifndef ArduinoMsgCodec_h
#define ArduinoMsgCodec_h

/*******************************************************************
 * MRLCOMM FUNCTION GENERATED INTERFACE
 * this file was generated by ArduinoMsgCodec and ArduinoMsgCodec.h.template
 */

///// INO GENERATED DEFINITION BEGIN //////
// {publishMRLCommError Integer} 
#define PUBLISH_MRLCOMM_ERROR		1
// {getVersion} 
#define GET_VERSION		2
// {publishVersion Integer} 
#define PUBLISH_VERSION		3
// {analogWrite int int} 
#define ANALOG_WRITE		4
// {controllerAttach Arduino int} 
#define CONTROLLER_ATTACH		5
// {createI2cDevice I2CControl int int} 
#define CREATE_I2C_DEVICE		6
// {deviceAttach DeviceControl Object[]} 
#define DEVICE_ATTACH		7
// {deviceDetach DeviceControl} 
#define DEVICE_DETACH		8
// {digitalWrite int int} 
#define DIGITAL_WRITE		9
// {disableBoardStatus} 
#define DISABLE_BOARD_STATUS		10
// {disablePin int} 
#define DISABLE_PIN		11
// {disablePins} 
#define DISABLE_PINS		12
// {enableBoardStatus int} 
#define ENABLE_BOARD_STATUS		13
// {enablePin int} 
#define ENABLE_PIN		14
// {getMrlPinType PinDefinition} 
#define GET_MRL_PIN_TYPE		15
// {i2cRead I2CControl int int byte[] int} 
#define I2C_READ		16
// {i2cWrite I2CControl int int byte[] int} 
#define I2C_WRITE		17
// {i2cWriteRead I2CControl int int byte[] int byte[] int} 
#define I2C_WRITE_READ		18
// {intsToString int[] int int} 
#define INTS_TO_STRING		19
// {isAttached} 
#define IS_ATTACHED		20
// {motorMove MotorControl} 
#define MOTOR_MOVE		21
// {motorMoveTo MotorControl} 
#define MOTOR_MOVE_TO		22
// {motorReset MotorControl} 
#define MOTOR_RESET		23
// {motorStop MotorControl} 
#define MOTOR_STOP		24
// {msgRoute} 
#define MSG_ROUTE		25
// {neoPixelWriteMatrix NeoPixel List} 
#define NEO_PIXEL_WRITE_MATRIX		26
// {onSensorData SensorData} 
#define ON_SENSOR_DATA		27
// {pinMode int int} 
#define PIN_MODE		28
// {publishAttachedDevice String} 
#define PUBLISH_ATTACHED_DEVICE		29
// {publishBoardInfo BoardInfo} 
#define PUBLISH_BOARD_INFO		30
// {publishBoardStatus BoardStatus} 
#define PUBLISH_BOARD_STATUS		31
// {publishDebug String} 
#define PUBLISH_DEBUG		32
// {publishMessageAck} 
#define PUBLISH_MESSAGE_ACK		33
// {publishPin PinData} 
#define PUBLISH_PIN		34
// {publishPinArray PinData[]} 
#define PUBLISH_PIN_ARRAY		35
// {publishPulse Long} 
#define PUBLISH_PULSE		36
// {publishPulseStop Integer} 
#define PUBLISH_PULSE_STOP		37
// {publishSensorData SensorData} 
#define PUBLISH_SENSOR_DATA		38
// {publishServoEvent Integer} 
#define PUBLISH_SERVO_EVENT		39
// {publishTrigger Pin} 
#define PUBLISH_TRIGGER		40
// {pulse int int int int} 
#define PULSE		41
// {pulseStop} 
#define PULSE_STOP		42
// {read int} 
#define READ		43
// {releaseI2cDevice I2CControl int int} 
#define RELEASE_I2C_DEVICE		44
// {sensorActivate SensorControl Object[]} 
#define SENSOR_ACTIVATE		45
// {sensorDeactivate SensorControl} 
#define SENSOR_DEACTIVATE		46
// {sensorPollingStart String} 
#define SENSOR_POLLING_START		47
// {sensorPollingStop String} 
#define SENSOR_POLLING_STOP		48
// {servoAttach ServoControl int} 
#define SERVO_ATTACH		49
// {servoDetach ServoControl} 
#define SERVO_DETACH		50
// {servoEventsEnabled ServoControl boolean} 
#define SERVO_EVENTS_ENABLED		51
// {servoSetSpeed ServoControl} 
#define SERVO_SET_SPEED		52
// {servoSweepStart ServoControl} 
#define SERVO_SWEEP_START		53
// {servoSweepStop ServoControl} 
#define SERVO_SWEEP_STOP		54
// {servoWrite ServoControl} 
#define SERVO_WRITE		55
// {servoWriteMicroseconds ServoControl int} 
#define SERVO_WRITE_MICROSECONDS		56
// {setDebounce int} 
#define SET_DEBOUNCE		57
// {setDebug boolean} 
#define SET_DEBUG		58
// {setDigitalTriggerOnly Boolean} 
#define SET_DIGITAL_TRIGGER_ONLY		59
// {setPWMFrequency Integer Integer} 
#define SET_PWMFREQUENCY		60
// {setSampleRate int} 
#define SET_SAMPLE_RATE		61
// {setSerialRate int} 
#define SET_SERIAL_RATE		62
// {setTrigger int int int} 
#define SET_TRIGGER		63
// {softReset} 
#define SOFT_RESET		64
// {write int int} 
#define WRITE		65
///// INO GENERATED DEFINITION END //////


/*******************************************************************
 * serial protocol functions
 */
#define MAGIC_NUMBER            170 // 10101010


/*******************************************************************
 * BOARD TYPE
 */
#define BOARD_TYPE_ID_UNKNOWN 0
#define BOARD_TYPE_ID_MEGA    1
#define BOARD_TYPE_ID_UNO     2

#if defined(ARDUINO_AVR_MEGA2560) || defined(ARDUINO_AVR_ADK)
  #define BOARD BOARD_TYPE_ID_MEGA
#elif defined(ARDUINO_AVR_UNO)
  #define BOARD BOARD_TYPE_ID_UNO
#else
  #define BOARD BOARD_TYPE_ID_UNKNOWN
#endif

#endif
