#ifndef ArduinoMsgCodec_h
#define ArduinoMsgCodec_h

/*******************************************************************
 * MRLCOMM FUNCTION GENERATED INTERFACE
 * this file was generated by ArduinoMsgCodec and ArduinoMsgCodec.h.template
 */

///// INO GENERATED DEFINITION BEGIN //////
// {publishMRLCommError Integer} 
#define PUBLISH_MRLCOMM_ERROR		1
// {getVersion} 
#define GET_VERSION		2
// {publishVersion Integer} 
#define PUBLISH_VERSION		3
// {analogWrite int int} 
#define ANALOG_WRITE		4
// {createI2cDevice I2CControl int int} 
#define CREATE_I2C_DEVICE		5
// {deviceAttach DeviceControl Object[]} 
#define DEVICE_ATTACH		6
// {deviceDetach DeviceControl} 
#define DEVICE_DETACH		7
// {digitalWrite int int} 
#define DIGITAL_WRITE		8
// {disableBoardStatus} 
#define DISABLE_BOARD_STATUS		9
// {disablePin int} 
#define DISABLE_PIN		10
// {enableBoardStatus int} 
#define ENABLE_BOARD_STATUS		11
// {enablePin int} 
#define ENABLE_PIN		12
// {getMrlPinType PinDefinition} 
#define GET_MRL_PIN_TYPE		13
// {i2cRead I2CControl int int byte[] int} 
#define I2C_READ		14
// {i2cWrite I2CControl int int byte[] int} 
#define I2C_WRITE		15
// {i2cWriteRead I2CControl int int byte[] int byte[] int} 
#define I2C_WRITE_READ		16
// {intsToString int[] int int} 
#define INTS_TO_STRING		17
// {isAttached} 
#define IS_ATTACHED		18
// {motorMove MotorControl} 
#define MOTOR_MOVE		19
// {motorMoveTo MotorControl} 
#define MOTOR_MOVE_TO		20
// {motorReset MotorControl} 
#define MOTOR_RESET		21
// {motorStop MotorControl} 
#define MOTOR_STOP		22
// {neoPixelWriteMatrix NeoPixel List} 
#define NEO_PIXEL_WRITE_MATRIX		23
// {onSensorData SensorData} 
#define ON_SENSOR_DATA		24
// {pinMode String String} 
#define PIN_MODE		25
// {publishAttachedDevice String} 
#define PUBLISH_ATTACHED_DEVICE		26
// {publishBoardInfo BoardInfo} 
#define PUBLISH_BOARD_INFO		27
// {publishBoardStatus BoardStatus} 
#define PUBLISH_BOARD_STATUS		28
// {publishDebug String} 
#define PUBLISH_DEBUG		29
// {publishMessageAck} 
#define PUBLISH_MESSAGE_ACK		30
// {publishPin PinData} 
#define PUBLISH_PIN		31
// {publishPinArray PinData[]} 
#define PUBLISH_PIN_ARRAY		32
// {publishPulse Long} 
#define PUBLISH_PULSE		33
// {publishPulseStop Integer} 
#define PUBLISH_PULSE_STOP		34
// {publishSensorData SensorData} 
#define PUBLISH_SENSOR_DATA		35
// {publishServoEvent Integer} 
#define PUBLISH_SERVO_EVENT		36
// {publishTrigger Pin} 
#define PUBLISH_TRIGGER		37
// {pulse int int int int} 
#define PULSE		38
// {pulseStop} 
#define PULSE_STOP		39
// {read String} 
#define READ		40
// {releaseI2cDevice I2CControl int int} 
#define RELEASE_I2C_DEVICE		41
// {sensorActivate SensorControl Object[]} 
#define SENSOR_ACTIVATE		42
// {sensorDeactivate SensorControl} 
#define SENSOR_DEACTIVATE		43
// {sensorPollingStart String} 
#define SENSOR_POLLING_START		44
// {sensorPollingStop String} 
#define SENSOR_POLLING_STOP		45
// {servoAttach ServoControl int} 
#define SERVO_ATTACH		46
// {servoDetach ServoControl} 
#define SERVO_DETACH		47
// {servoEventsEnabled ServoControl boolean} 
#define SERVO_EVENTS_ENABLED		48
// {servoSetSpeed ServoControl} 
#define SERVO_SET_SPEED		49
// {servoSweepStart ServoControl} 
#define SERVO_SWEEP_START		50
// {servoSweepStop ServoControl} 
#define SERVO_SWEEP_STOP		51
// {servoWrite ServoControl} 
#define SERVO_WRITE		52
// {servoWriteMicroseconds ServoControl int} 
#define SERVO_WRITE_MICROSECONDS		53
// {setDebounce int} 
#define SET_DEBOUNCE		54
// {setDebug boolean} 
#define SET_DEBUG		55
// {setDigitalTriggerOnly Boolean} 
#define SET_DIGITAL_TRIGGER_ONLY		56
// {setPWMFrequency Integer Integer} 
#define SET_PWMFREQUENCY		57
// {setSampleRate int} 
#define SET_SAMPLE_RATE		58
// {setSerialRate int} 
#define SET_SERIAL_RATE		59
// {setTrigger int int int} 
#define SET_TRIGGER		60
// {softReset} 
#define SOFT_RESET		61
// {write int int} 
#define WRITE		62
///// INO GENERATED DEFINITION END //////

#define CONTROLLER_ATTACH 80
#define MSG_ROUTE 81
#define ENABLE_PIN_EVENTS 82
#define DISABLE_PIN_EVENTS 83
/*******************************************************************
 * serial protocol functions
 */
#define MAGIC_NUMBER            170 // 10101010


/*******************************************************************
 * BOARD TYPE
 */
#define BOARD_TYPE_ID_UNKNOWN 0
#define BOARD_TYPE_ID_MEGA    1
#define BOARD_TYPE_ID_UNO     2

#if defined(ARDUINO_AVR_MEGA2560)
  #define BOARD BOARD_TYPE_ID_MEGA
#elif defined(ARDUINO_AVR_ADK)
  #define BOARD BOARD_TYPE_ID_MEGA
#elif defined(ARDUINO_AVR_UNO)
  #define BOARD BOARD_TYPE_ID_UNO
#else
  #define BOARD BOARD_TYPE_ID_UNKNOWN
#endif

#endif
