!!org.myrobotlab.service.config.RuntimeConfig
enableCli: true
id: null
listeners: [
  ]
locale: null
logLevel: info
peers: null
registry:
- runtime
- security
- webgui
- solr
- audiofile
- docproc
- fileconnector
resource: resource
type: Runtime
virtual: false
